### ISSUE TITLE
Seconds

### ISSUE THREAD

**Issue by Steellgold** [omarkhairy21/cron-toolkit-ts#2]
It's amazing your project! But you can add the seconds ?

**Comment by omarkhairy21** [comment]
Thanks for your feedback😊 I was waiting for feedback from the community to add more features I will start with with your request and add seconds functions

**Comment by omarkhairy21** [comment]
I just checked it seems seconds would not be standardized so I would think a good interface for that. if you have any ideas let me know

**Comment by omarkhairy21** [comment]
Added now you can use seconds by calling `useNonStandard()` for examples:

```typeScript
const every5Seconds = cron.useNonStandard().everyCustomSecond(5); // */5 * * * * *
const every10Seconds = cron.useNonStandard().every15Seconds(); // */10 * * * * *
const every45Seconds = cron.useNonStandard().every45Seconds(); // */45 * * * * *
```
